# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to NuGet

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/UniChain.csproj
    - name: Build
      run: dotnet build --no-restore ./src/UniChain.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/UniChain.csproj
    - name: Pack
      run: dotnet pack -c Release ./src/UniChain.csproj -o ./bin/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Package
        path: |
          ./bin/Unichain.*.nupkg
          !./bin/Unichain.CLI.*.nupkg
        retention-days: 0 # default
      
